### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by marcoturi** [jonschlinkert/placeholders#1]
Adding this lib with yarn gives this following warn:
```
WARNING in ./node_modules/expand/utils.js
4:34-41 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

```

**Comment by doowb** [comment]
@marcoturi will you show the `yarn` command you run to get the warning? Also, please include additional information like OS, node, and yarn versions.

**Comment by marcoturi** [comment]
cmd: yarn install
yarn: 1.2.1 
node: 6.11.1
OS: Mac

**Comment by doowb** [comment]
This seems like a bug with yarn. Yarn shouldn't be doing any code analysis when installing packages. Also it looks like a warning so you should still be able to use the module. 

I'm going to close this because I don't think it's a bug in this library. I would suggest using npm or open an issue on yarn. If you find out more information, please feel free to post back here.
